#!/usr/bin/env python3
"""
Create consolidated schema file for DB initialization.

Usage:
  python backend/db/package_schema_and_seed.py

Nota: Los seeds están en la carpeta seeds/ (uno por tabla).
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
PACK_DIR = ROOT / 'packaged'
PACK_DIR.mkdir(exist_ok=True)

# Order matters: base schema + tables + roles/permissions + migrations
SCHEMA_SOURCE_FILES = [
    ROOT / '01_base_schema_mysql.sql',      # Tablas base en MySQL con tus modificaciones
    ROOT / 'create_supplies_tables.sql',    # supplies + supplies_movements
    ROOT / 'create_orders_tables.sql',      # sales_orders + production_orders
    ROOT / 'roles_permissions.sql',         # roles + permissions + role_permissions
    # Migraciones (para verificar completitud)
    ROOT / 'add_password_reset.sql',
    ROOT / 'add_must_change_password.sql',
    ROOT / 'add_expiry_date.sql',
    ROOT / 'check_supplies_schema.sql'
]

OUT_SCHEMA = PACK_DIR / 'full_schema.sql'

insert_re = re.compile(r"^\s*INSERT\s+INTO\b", re.IGNORECASE)

def append_schema(outf, path):
    if not path.exists():
        print(f"Skipping missing schema source: {path}")
        return
    with path.open('r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            if insert_re.match(line):
                # skip INSERTs when building schema
                continue
            outf.write(line)
    outf.write('\n-- ---- end of ' + str(path.name) + '\n\n')

def main():
    print(f"Writing schema -> {OUT_SCHEMA}")
    with OUT_SCHEMA.open('w', encoding='utf-8') as out:
        out.write('-- Consolidated schema generated by package_schema_and_seed.py\n')
        out.write('-- Review before applying in production\n\n')
        for p in SCHEMA_SOURCE_FILES:
            append_schema(out, p)

    print('Done.')
    print(f' - {OUT_SCHEMA}')
    print('')
    print('Para los seeds, usa los archivos en: seeds/')

if __name__ == '__main__':
    main()
