-- Consolidated schema generated by package_schema_and_seed.py
-- Review before applying in production

-- =====================================================================
-- SCHEMA BASE - MYSQL (convertido desde init.sql con modificaciones)
-- =====================================================================
-- Incluye: reset_token, must_change_password, expiry_date, role_id

-- Tabla de usuarios para autenticación (CON MODIFICACIONES)
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  role VARCHAR(20) DEFAULT 'user',
  role_id INT DEFAULT 1,
  must_change_password TINYINT(1) DEFAULT 0,
  reset_token VARCHAR(255) NULL,
  reset_token_expires DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de productos (CON MODIFICACIONES)
CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  sku VARCHAR(50) UNIQUE NOT NULL,
  description LONGTEXT,
  category VARCHAR(50),
  price DECIMAL(10, 2),
  stock_quantity INT DEFAULT 0,
  min_stock_level INT DEFAULT 10,
  image_url VARCHAR(255),
  is_active TINYINT(1) DEFAULT 1,
  expiry_date DATE DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_products_category (category),
  KEY idx_products_expiry (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de inventario
CREATE TABLE IF NOT EXISTS inventory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT,
  warehouse_location VARCHAR(100),
  quantity INT,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  KEY idx_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de clientes/proveedores
CREATE TABLE IF NOT EXISTS suppliers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_name VARCHAR(100) NOT NULL,
  contact_person VARCHAR(100),
  email VARCHAR(100),
  phone VARCHAR(20),
  address LONGTEXT,
  city VARCHAR(50),
  country VARCHAR(50),
  payment_terms VARCHAR(50),
  category VARCHAR(100),
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de clientes
CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100),
  phone VARCHAR(20),
  address LONGTEXT,
  city VARCHAR(50),
  country VARCHAR(50),
  customer_type VARCHAR(20),
  status VARCHAR(20) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de órdenes
CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  customer_id INT,
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  delivery_date DATE,
  total_amount DECIMAL(10, 2),
  status VARCHAR(20) DEFAULT 'pending',
  notes LONGTEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  KEY idx_orders_customer (customer_id),
  KEY idx_orders_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de detalles de órdenes
CREATE TABLE IF NOT EXISTS order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT,
  quantity INT,
  unit_price DECIMAL(10, 2),
  total DECIMAL(10, 2),
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de facturas
CREATE TABLE IF NOT EXISTS invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_number VARCHAR(50) UNIQUE NOT NULL,
  order_id INT,
  customer_id INT,
  issue_date DATE,
  due_date DATE,
  total_amount DECIMAL(10, 2),
  paid_amount DECIMAL(10, 2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  KEY idx_invoices_customer (customer_id),
  KEY idx_invoices_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de empleados
CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100),
  phone VARCHAR(20),
  position VARCHAR(50),
  department VARCHAR(50),
  hire_date DATE,
  salary DECIMAL(10, 2),
  status VARCHAR(20) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_employees_department (department)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de reportes
CREATE TABLE IF NOT EXISTS sales_reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  report_date DATE,
  total_sales DECIMAL(10, 2),
  total_purchases DECIMAL(10, 2),
  product_category VARCHAR(50),
  quantity_sold INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---- end of 01_base_schema_mysql.sql

-- Crear tabla supplies completa con todos los campos necesarios
CREATE TABLE IF NOT EXISTS supplies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  sku VARCHAR(50) UNIQUE NOT NULL,
  description TEXT,
  category VARCHAR(50),
  price DECIMAL(10, 2),
  stock_quantity INT DEFAULT 0,
  min_stock_level INT DEFAULT 10,
  unit VARCHAR(20),
  image_url VARCHAR(255),
  supplier_id INT,
  expiry_date DATE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Crear tabla para registrar movimientos de supplies
CREATE TABLE IF NOT EXISTS supplies_movements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supply_id INT NOT NULL,
  movement_type VARCHAR(50) DEFAULT 'ajuste',
  quantity_change INT NOT NULL,
  previous_quantity INT DEFAULT 0,
  new_quantity INT DEFAULT 0,
  reason VARCHAR(255),
  notes TEXT,
  user_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (supply_id) REFERENCES supplies(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ---- end of create_supplies_tables.sql

-- Tabla de órdenes de venta
CREATE TABLE IF NOT EXISTS sales_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  customer_id INT,
  customer_name VARCHAR(100),
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  delivery_date DATE,
  total_amount DECIMAL(10, 2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'pending',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customers(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tabla de items de órdenes de venta
CREATE TABLE IF NOT EXISTS sales_order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sales_order_id INT NOT NULL,
  product_id INT,
  quantity INT NOT NULL,
  unit_price DECIMAL(10, 2),
  total DECIMAL(10, 2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tabla de insumos para órdenes de venta
CREATE TABLE IF NOT EXISTS sales_order_insumos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sales_order_id INT NOT NULL,
  insumo_id INT,
  quantity_required DECIMAL(10, 2),
  unit VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tabla de órdenes de producción
CREATE TABLE IF NOT EXISTS production_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  responsible_employee_id INT,
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  due_date DATE,
  status VARCHAR(20) DEFAULT 'pendiente',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id),
  FOREIGN KEY (responsible_employee_id) REFERENCES employees(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tabla de insumos para órdenes de producción
CREATE TABLE IF NOT EXISTS production_order_insumos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  production_order_id INT NOT NULL,
  insumo_id INT NOT NULL,
  quantity_required DECIMAL(10, 2) NOT NULL,
  quantity_used DECIMAL(10, 2) DEFAULT 0,
  unit VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (production_order_id) REFERENCES production_orders(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ---- end of create_orders_tables.sql

-- ============================================
-- SCRIPT: Crear Tabla de Roles y Permisos
-- ============================================

-- Tabla de Roles
CREATE TABLE IF NOT EXISTS roles (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabla de Permisos
CREATE TABLE IF NOT EXISTS permissions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL UNIQUE,
  description VARCHAR(255),
  module VARCHAR(50),
  action VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de relación Roles - Permisos
CREATE TABLE IF NOT EXISTS role_permissions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  role_id INT NOT NULL,
  permission_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
  UNIQUE KEY unique_role_permission (role_id, permission_id)
);

-- ============================================
-- INSERTAR ROLES
-- ============================================

('Administrador General', 'Acceso total al sistema'),
('Supervisor de Stock', 'Responsable de inventario y suministros'),
('Encargado de Ventas', 'Encargado de ventas y facturación'),
('Panadero', 'Responsable de la producción');

-- Modificar tabla usuarios para agregar role_id
ALTER TABLE users ADD COLUMN role_id INT DEFAULT 1;

-- Actualizar usuarios existentes con role_id válido
UPDATE users SET role_id = 1 WHERE role_id IS NULL;

-- Remover foreign key antigua si existe
ALTER TABLE users DROP FOREIGN KEY fk_users_role_id;

-- Agregar foreign key después de los datos
ALTER TABLE users ADD CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET DEFAULT;

-- ============================================
-- INSERTAR PERMISOS
-- ============================================

-- Dashboard
('dashboard.view', 'dashboard', 'read', 'Ver dashboard'),
('dashboard.export', 'dashboard', 'write', 'Exportar datos del dashboard');

-- Inventario
('inventory.view', 'inventory', 'read', 'Ver inventario'),
('inventory.create', 'inventory', 'write', 'Crear movimientos de inventario'),
('inventory.edit', 'inventory', 'write', 'Editar movimientos'),
('inventory.delete', 'inventory', 'delete', 'Eliminar movimientos');

-- Productos
('products.view', 'products', 'read', 'Ver productos'),
('products.create', 'products', 'write', 'Crear productos'),
('products.edit', 'products', 'write', 'Editar productos'),
('products.delete', 'products', 'delete', 'Eliminar productos');

-- Órdenes
('orders.view', 'orders', 'read', 'Ver órdenes'),
('orders.create', 'orders', 'write', 'Crear órdenes'),
('orders.edit', 'orders', 'write', 'Editar órdenes'),
('orders.delete', 'orders', 'delete', 'Eliminar órdenes');

-- Órdenes de Producción
('production_orders.view', 'production_orders', 'read', 'Ver órdenes de producción'),
('production_orders.create', 'production_orders', 'write', 'Crear órdenes de producción'),
('production_orders.edit', 'production_orders', 'write', 'Editar órdenes de producción'),
('production_orders.delete', 'production_orders', 'delete', 'Eliminar órdenes de producción');

-- Órdenes de Venta
('sales_orders.view', 'sales_orders', 'read', 'Ver órdenes de venta'),
('sales_orders.create', 'sales_orders', 'write', 'Crear órdenes de venta'),
('sales_orders.edit', 'sales_orders', 'write', 'Editar órdenes de venta'),
('sales_orders.delete', 'sales_orders', 'delete', 'Eliminar órdenes de venta');

-- Facturación
('billing.view', 'billing', 'read', 'Ver facturas'),
('billing.create', 'billing', 'write', 'Crear facturas'),
('billing.edit', 'billing', 'write', 'Editar facturas'),
('billing.delete', 'billing', 'delete', 'Eliminar facturas'),
('billing.pay', 'billing', 'write', 'Registrar pagos');

-- Empleados
('employees.view', 'employees', 'read', 'Ver empleados'),
('employees.create', 'employees', 'write', 'Crear empleados'),
('employees.edit', 'employees', 'write', 'Editar empleados'),
('employees.delete', 'employees', 'delete', 'Eliminar empleados');

-- Reportes
('reports.view', 'reports', 'read', 'Ver reportes'),
('reports.export', 'reports', 'write', 'Exportar reportes'),
('reports.production', 'reports', 'read', 'Ver reportes de producción'),
('reports.sales', 'reports', 'read', 'Ver reportes de ventas'),
('reports.inventory', 'reports', 'read', 'Ver reportes de inventario');

-- Proveedores
('suppliers.view', 'suppliers', 'read', 'Ver proveedores'),
('suppliers.create', 'suppliers', 'write', 'Crear proveedores'),
('suppliers.edit', 'suppliers', 'write', 'Editar proveedores'),
('suppliers.delete', 'suppliers', 'delete', 'Eliminar proveedores');

-- Suministros
('supplies.view', 'supplies', 'read', 'Ver suministros'),
('supplies.create', 'supplies', 'write', 'Crear suministros'),
('supplies.edit', 'supplies', 'write', 'Editar suministros'),
('supplies.delete', 'supplies', 'delete', 'Eliminar suministros');

-- Notificaciones
('notifications.view', 'notifications', 'read', 'Ver notificaciones'),
('notifications.manage', 'notifications', 'write', 'Gestionar notificaciones');

-- Configuración
('settings.view', 'settings', 'read', 'Ver configuración'),
('settings.edit', 'settings', 'write', 'Editar configuración'),
('users.manage', 'settings', 'write', 'Gestionar usuarios');

-- ============================================
-- ASIGNAR PERMISOS A ROLES
-- ============================================

-- ADMINISTRADOR GENERAL (ID: 1) - Acceso Total
SELECT 1, id FROM permissions;

-- SUPERVISOR DE STOCK (ID: 2) - Inventario, Suministros, Proveedores
SELECT 2, id FROM permissions WHERE module IN (
  'dashboard', 'inventory', 'products', 'supplies', 'suppliers', 'reports', 'notifications'
) AND (action = 'read' OR module IN ('inventory', 'supplies', 'suppliers') AND action IN ('read', 'write'));

-- ENCARGADO DE VENTAS (ID: 3) - Ventas y Facturación
SELECT 3, id FROM permissions WHERE module IN (
  'dashboard', 'sales_orders', 'billing', 'products', 'inventory', 'notifications'
) AND (action = 'read' OR (module IN ('sales_orders', 'billing') AND action = 'write'));

-- PANADERO (ID: 4) - Producción
SELECT 4, id FROM permissions WHERE module IN (
  'dashboard', 'production_orders', 'supplies', 'notifications', 'reports'
) AND action IN ('read', 'write');

-- ============================================
-- QUERY DE PRUEBA: Ver permisos por rol
-- ============================================

-- SELECT r.name as Role, p.module, p.name, p.action 
-- FROM roles r
-- LEFT JOIN role_permissions rp ON r.id = rp.role_id
-- LEFT JOIN permissions p ON rp.permission_id = p.id
-- ORDER BY r.name, p.module, p.name;

-- ---- end of roles_permissions.sql

-- Agregar columnas para recuperación de contraseña
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS reset_token VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS reset_token_expires DATETIME NULL;

-- Verificar que se agregaron
-- SHOW COLUMNS FROM users LIKE 'reset_token';
-- ---- end of add_password_reset.sql

-- Agregar columna must_change_password a tabla users
ALTER TABLE users ADD COLUMN must_change_password BOOLEAN DEFAULT FALSE;

-- ---- end of add_must_change_password.sql

-- Agregar campo de fecha de caducidad a productos
ALTER TABLE products ADD COLUMN IF NOT EXISTS expiry_date DATE DEFAULT NULL;

-- Agregar índice para búsquedas rápidas de productos vencidos
CREATE INDEX IF NOT EXISTS idx_products_expiry ON products(expiry_date);

-- Agregar campo de fecha de caducidad a insumos
ALTER TABLE supplies ADD COLUMN IF NOT EXISTS expiry_date DATE DEFAULT NULL;

-- Agregar índice para búsquedas rápidas de insumos vencidos
CREATE INDEX IF NOT EXISTS idx_supplies_expiry ON supplies(expiry_date);

-- Tabla de alertas de caducidad
CREATE TABLE IF NOT EXISTS expiry_alerts (
  id SERIAL PRIMARY KEY,
  product_id INT,
  supply_id INT,
  alert_type VARCHAR(50), -- 'expired', 'expiring_soon', 'expiring_this_week'
  expiry_date DATE NOT NULL,
  days_until_expiry INT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  FOREIGN KEY (supply_id) REFERENCES supplies(id) ON DELETE CASCADE,
  CHECK ((product_id IS NOT NULL AND supply_id IS NULL) OR (product_id IS NULL AND supply_id IS NOT NULL))
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Índices para alertas
CREATE INDEX IF NOT EXISTS idx_expiry_alerts_product ON expiry_alerts(product_id);
CREATE INDEX IF NOT EXISTS idx_expiry_alerts_supply ON expiry_alerts(supply_id);
CREATE INDEX IF NOT EXISTS idx_expiry_alerts_type ON expiry_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_expiry_alerts_active ON expiry_alerts(is_active);

-- ---- end of add_expiry_date.sql

-- Verificar estructura de la tabla supplies
DESCRIBE supplies;

-- Si la tabla existe, mostrar su información
SELECT COLUMN_NAME, COLUMN_TYPE FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'supplies' AND TABLE_SCHEMA = DATABASE();

-- ---- end of check_supplies_schema.sql

